In [998]:
# Initial imports
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn import preprocessing
import hvplot.pandas
import datetime

%matplotlib inline

In [866]:
# Set the random seed for reproducibility
# Note: This is used for model prototyping, but it is good practice to comment this out and run multiple experiments to evaluate your model.
from numpy.random import seed

seed(1)
from tensorflow import random

random.set_seed(2)

In [867]:
#Reading the .csv files

fb_csv = Path("../Resources/fb_data.csv")
fb_df = pd.read_csv(fb_csv)
fb_df['Date'] = pd.to_datetime(fb_df.Date).dt.date

aapl_csv = Path("../Resources/aapl_data.csv")
aapl_df = pd.read_csv(aapl_csv)
aapl_df['Date'] = pd.to_datetime(aapl_df.Date).dt.date

amzn_csv = Path("../Resources/amzn_data.csv")
amzn_df = pd.read_csv(amzn_csv)
amzn_df['Date'] = pd.to_datetime(amzn_df.Date).dt.date

nflx_csv = Path("../Resources/nflx_data.csv")
nflx_df = pd.read_csv(nflx_csv)
nflx_df['Date'] = pd.to_datetime(nflx_df.Date).dt.date

googl_csv = Path("../Resources/googl_data.csv")
googl_df = pd.read_csv(googl_csv)
googl_df['Date'] = pd.to_datetime(googl_df.Date).dt.date

fb_df.set_index("Date", inplace = True)
aapl_df.set_index("Date", inplace = True)
amzn_df.set_index("Date", inplace = True)
nflx_df.set_index("Date", inplace = True)
googl_df.set_index("Date", inplace = True)

In [868]:
#fb_df = fb_df.drop(columns=["Open", "High", "Low"])
fb_df_scaled = fb_df

#aapl_df = aapl_df.drop(columns=["High", "Low"])
aapl_df_scaled = aapl_df

#amzn_df = amzn_df.drop(columns=["High", "Low"])
amzn_df_scaled = amzn_df

#nflx_df = nflx_df.drop(columns=["High", "Low"])
nflx_df_scaled = nflx_df

#googl_df = googl_df.drop(columns=["High", "Low"])
googl_df_scaled = googl_df

In [869]:
#Scaling all the columns

x = fb_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["Open0_1"] = x_scaled

x = fb_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["High0_1"] = x_scaled

x = fb_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["Low0_1"] = x_scaled

x = fb_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["Volume"] = x_scaled

x = fb_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["sentiment"] = x_scaled

x = fb_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["RSI"] = x_scaled

fb_df_scaled = fb_df_scaled.drop(columns=["Open", "High", "Low"])
#fb_df_scaled.dropna(inplace=True)
fb_df_scaled=fb_df_scaled.fillna(0)

x = aapl_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["Open0_1"] = x_scaled

x = aapl_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["High0_1"] = x_scaled

x = aapl_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["Low0_1"] = x_scaled

x = aapl_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["Volume"] = x_scaled
aapl_df_scaled

x = aapl_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["sentiment"] = x_scaled
aapl_df_scaled

x = aapl_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["RSI"] = x_scaled

aapl_df_scaled = aapl_df_scaled.drop(columns=["Open", "High", "Low"])
#aapl_df_scaled.dropna(inplace=True)
aapl_df_scaled=aapl_df_scaled.fillna(0)

x = amzn_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["Open0_1"] = x_scaled

x = amzn_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["High0_1"] = x_scaled

x = amzn_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["Low0_1"] = x_scaled

x = amzn_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["Volume"] = x_scaled

x = amzn_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["sentiment"] = x_scaled

x = amzn_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["RSI"] = x_scaled

amzn_df_scaled = amzn_df_scaled.drop(columns=["Open", "High", "Low"])
#amzn_df_scaled.dropna(inplace=True)
amzn_df_scaled=amzn_df_scaled.fillna(0)

x = nflx_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["Open0_1"] = x_scaled

x = nflx_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["High0_1"] = x_scaled

x = nflx_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["Low0_1"] = x_scaled

x = nflx_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["Volume"] = x_scaled

x = nflx_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["sentiment"] = x_scaled

x = nflx_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["RSI"] = x_scaled

nflx_df_scaled = nflx_df_scaled.drop(columns=["Open", "High", "Low"])
#nflx_df_scaled.dropna(inplace=True)
nflx_df_scaled=nflx_df_scaled.fillna(0)

x = googl_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["Open0_1"] = x_scaled

x = googl_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["High0_1"] = x_scaled

x = googl_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["Low0_1"] = x_scaled

x = googl_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["Volume"] = x_scaled

x = googl_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["sentiment"] = x_scaled

x = googl_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["RSI"] = x_scaled

googl_df_scaled = googl_df_scaled.drop(columns=["Open", "High", "Low"])
#googl_df_scaled.dropna(inplace=True)
googl_df_scaled=googl_df_scaled.fillna(0)
googl_df_scaled

Close    Volume  Volatility  sentiment       RSI   Open0_1  \
Date                                                                        
2019-01-02  1053.240  0.152773    0.279226   0.262816  0.000000  0.000000   
2019-01-03  1026.505  0.189410    0.297727   0.321999  0.000000  0.069685   
2019-01-04  1076.550  0.234292    0.498923   0.419047  0.000000  0.042844   
2019-01-07  1076.010  0.248849    0.073502   0.524146  0.000000  0.159650   
2019-01-08  1085.510  0.163034    0.007682   0.760071  0.000000  0.170932   
...              ...       ...         ...        ...       ...       ...   
2019-12-24  1344.740  0.015894    0.025493   0.372467  0.663397  0.959056   
2019-12-26  1362.160  0.074121    0.113546   0.523969  0.790973  0.948189   
2019-12-27  1354.640  0.063306    0.063423   0.526298  0.701485  1.000000   
2019-12-30  1340.470  0.057970    0.107363   0.435962  0.554641  0.978652   
2019-12-31  1338.120  0.038471    0.012810   0.698379  0.532288  0.916241   

             High0_1    Low0_1  
Date                            
2019-01-02  0.034030  0.008786  
2019-01-03  0.051282  0.000000  
2019-01-04  0.094616  0.043825  
2019-01-07  0.103132  0.121798  
2019-01-08  0.136721  0.139064  
...              ...       ...  
2019-12-24  0.952503  0.973278  
2019-12-26  0.987794  0.977346  
2019-12-27  1.000000  1.000000  
2019-12-30  0.968240  0.954133  
2019-12-31  0.916706  0.936878  

[252 rows x 8 columns]

In [870]:
def window_data(df, window, feature_col_number, target_col_number):
    """
    This function accepts the column number for the features (X) and the target (y).
    It chunks the data up with a rolling window of Xt - window to predict Xt.
    It returns two numpy arrays of X and y.
    """
    X = []
    y = []
    for i in range(len(df) - window - 1):
        features = df.iloc[i : (i + window), 1:6].values
        X.append(features)
        target = df.iloc[(i + window), target_col_number]
        y.append(target)
    return np.array(X), np.array(y).reshape(-1, 1)

In [871]:
# Creating the features (X) and target (y) data using the window_data() function.
window_size = 5

feature_column = 0
target_column = 0
X_fb, y_fb = window_data(fb_df_scaled, window_size, feature_column, target_column)
#print (f"X_fb sample values:\n{X_fb[:5]} \n")
#print (f"y_fb sample values:\n{y_fb[:5]}")

X_aapl, y_aapl = window_data(aapl_df_scaled, window_size, feature_column, target_column)
#print (f"X_aapl sample values:\n{X_aapl[:5]} \n")
#print (f"y_aapl sample values:\n{y_aapl[:5]}")

X_amzn, y_amzn = window_data(amzn_df_scaled, window_size, feature_column, target_column)
#print (f"X_amzn sample values:\n{X_amzn[:5]} \n")
#print (f"y_amzn sample values:\n{y_amzn[:5]}")

X_nflx, y_nflx = window_data(nflx_df_scaled, window_size, feature_column, target_column)
#print (f"X_nflx sample values:\n{X_nflx[:5]} \n")
#print (f"y_nflx sample values:\n{y_nflx[:5]}")

X_googl, y_googl = window_data(googl_df_scaled, window_size, feature_column, target_column)
#print (f"X_googl sample values:\n{X_googl[:5]} \n")
#print (f"y_googl sample values:\n{y_googl[:5]}")


In [872]:
# Use 90% of the data for training and the remainder for testing
split = int(0.90 * len(X_fb))
X_fb_train = X_fb[: split - 1]
X_fb_test = X_fb[split:]
y_fb_train = y_fb[: split - 1]
y_fb_test = y_fb[split:]

X_aapl_train = X_aapl[: split - 1]
X_aapl_test = X_aapl[split:]
y_aapl_train = y_aapl[: split - 1]
y_aapl_test = y_aapl[split:]

X_amzn_train = X_amzn[: split - 1]
X_amzn_test = X_amzn[split:]
y_amzn_train = y_amzn[: split - 1]
y_amzn_test = y_amzn[split:]

X_nflx_train = X_nflx[: split - 1]
X_nflx_test = X_nflx[split:]
y_nflx_train = y_nflx[: split - 1]
y_nflx_test = y_nflx[split:]

X_googl_train = X_googl[: split - 1]
X_googl_test = X_googl[split:]
y_googl_train = y_googl[: split - 1]
y_googl_test = y_googl[split:]


In [873]:
# Use the MinMaxScaler to scale data between 0 and 1.
from sklearn.preprocessing import MinMaxScaler

scaler_fb = MinMaxScaler()
scaler_fb.fit(y_fb)
y_fb_train = scaler_fb.transform(y_fb_train)
y_fb_test = scaler_fb.transform(y_fb_test)

scaler_aapl = MinMaxScaler()
scaler_aapl.fit(y_aapl)
y_aapl_train = scaler_aapl.transform(y_aapl_train)
y_aapl_test = scaler_aapl.transform(y_aapl_test)

scaler_amzn = MinMaxScaler()
scaler_amzn.fit(y_amzn)
y_amzn_train = scaler_amzn.transform(y_amzn_train)
y_amzn_test = scaler_amzn.transform(y_amzn_test)

scaler_nflx = MinMaxScaler()
scaler_nflx.fit(y_nflx)
y_nflx_train = scaler_nflx.transform(y_nflx_train)
y_nflx_test = scaler_nflx.transform(y_nflx_test)

scaler_googl = MinMaxScaler()
scaler_googl.fit(y_googl)
y_googl_train = scaler_googl.transform(y_googl_train)
y_googl_test = scaler_googl.transform(y_googl_test)


In [874]:
X_fb_train = X_fb_train.reshape((X_fb_train.shape[0], X_fb_train.shape[1], 5))
X_fb_test = X_fb_test.reshape((X_fb_test.shape[0], X_fb_test.shape[1], 5))
#print (f"X_train sample values:\n{X_fb_train[:5]} \n")
#print (f"X_test sample values:\n{X_fb_test[:5]}")

X_aapl_train = X_aapl_train.reshape((X_aapl_train.shape[0], X_aapl_train.shape[1], 5))
X_aapl_test = X_aapl_test.reshape((X_aapl_test.shape[0], X_aapl_test.shape[1], 5))
#print (f"X_train sample values:\n{X_aapl_train[:5]} \n")
#print (f"X_test sample values:\n{X_aapl_test[:5]}")

X_amzn_train = X_amzn_train.reshape((X_amzn_train.shape[0], X_amzn_train.shape[1], 5))
X_amzn_test = X_amzn_test.reshape((X_amzn_test.shape[0], X_amzn_test.shape[1], 5))
#print (f"X_train sample values:\n{X_amzn_train[:5]} \n")
#print (f"X_test sample values:\n{X_amzn_test[:5]}")

X_nflx_train = X_nflx_train.reshape((X_nflx_train.shape[0], X_nflx_train.shape[1], 5))
X_nflx_test = X_nflx_test.reshape((X_nflx_test.shape[0], X_nflx_test.shape[1], 5))
#print (f"X_train sample values:\n{X_nflx_train[:5]} \n")
#print (f"X_test sample values:\n{X_nflx_test[:5]}")

X_googl_train = X_googl_train.reshape((X_googl_train.shape[0], X_googl_train.shape[1], 5))
X_googl_test = X_googl_test.reshape((X_googl_test.shape[0], X_googl_test.shape[1], 5))
print (f"X_train sample values:\n{X_googl_train[:5]} \n")
print (f"X_test sample values:\n{X_googl_test[:5]}")


X_train sample values:
[[[0.15277328 0.27922631 0.26281589 0.         0.        ]
  [0.18941024 0.29772725 0.32199852 0.         0.06968527]
  [0.2342916  0.49892313 0.4190467  0.         0.04284442]
  [0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.76007102 0.         0.1709323 ]]

 [[0.18941024 0.29772725 0.32199852 0.         0.06968527]
  [0.2342916  0.49892313 0.4190467  0.         0.04284442]
  [0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.76007102 0.         0.1709323 ]
  [0.11760959 0.04333437 0.57968104 0.         0.18049287]]

 [[0.2342916  0.49892313 0.4190467  0.         0.04284442]
  [0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.76007102 0.         0.1709323 ]
  [0.11760959 0.04333437 0.57968104 0.         0.18049287]
  [0.10625191 0.02998816 0.11774981 0.         0.14174584]]

 [[0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.

In [875]:
# Import required Keras modules
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [876]:
# Define the LSTM RNN model.
model_fb = Sequential()

number_units = 10
dropout_fraction = 0.1

# Layer 1
model_fb.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_fb_train.shape[1], 5))
    )
model_fb.add(Dropout(dropout_fraction))
# Layer 2
model_fb.add(LSTM(units=number_units, return_sequences=True))
model_fb.add(Dropout(dropout_fraction))
# Layer 3
model_fb.add(LSTM(units=number_units))
model_fb.add(Dropout(dropout_fraction))
# Output layer
model_fb.add(Dense(1))

model_aapl = Sequential()

# Layer 1
model_aapl.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_aapl_train.shape[1], 5))
    )
model_aapl.add(Dropout(dropout_fraction))
# Layer 2
model_aapl.add(LSTM(units=number_units, return_sequences=True))
model_aapl.add(Dropout(dropout_fraction))
# Layer 3
model_aapl.add(LSTM(units=number_units))
model_aapl.add(Dropout(dropout_fraction))
# Output layer
model_aapl.add(Dense(1))

model_amzn = Sequential()

# Layer 1
model_amzn.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_amzn_train.shape[1], 5))
    )
model_amzn.add(Dropout(dropout_fraction))
# Layer 2
model_amzn.add(LSTM(units=number_units, return_sequences=True))
model_amzn.add(Dropout(dropout_fraction))
# Layer 3
model_amzn.add(LSTM(units=number_units))
model_amzn.add(Dropout(dropout_fraction))
# Output layer
model_amzn.add(Dense(1))

model_nflx = Sequential()

# Layer 1
model_nflx.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_nflx_train.shape[1], 5))
    )
model_nflx.add(Dropout(dropout_fraction))
# Layer 2
model_nflx.add(LSTM(units=number_units, return_sequences=True))
model_nflx.add(Dropout(dropout_fraction))
# Layer 3
model_nflx.add(LSTM(units=number_units))
model_nflx.add(Dropout(dropout_fraction))
# Output layer
model_nflx.add(Dense(1))

model_googl = Sequential()

# Layer 1
model_googl.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_googl_train.shape[1], 5))
    )
model_googl.add(Dropout(dropout_fraction))
# Layer 2
model_googl.add(LSTM(units=number_units, return_sequences=True))
model_googl.add(Dropout(dropout_fraction))
# Layer 3
model_googl.add(LSTM(units=number_units))
model_googl.add(Dropout(dropout_fraction))
# Output layer
model_googl.add(Dense(1))


In [877]:
# Compile the model
model_fb.compile(optimizer="adam", loss="mean_squared_error")
model_aapl.compile(optimizer="adam", loss="mean_squared_error")
model_amzn.compile(optimizer="adam", loss="mean_squared_error")
model_nflx.compile(optimizer="adam", loss="mean_squared_error")
model_googl.compile(optimizer="adam", loss="mean_squared_error")

In [878]:
# Summarize the model
model_fb.summary()

Model: "sequential_90"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_270 (LSTM)              (None, 5, 10)             640       
_________________________________________________________________
dropout_270 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_271 (LSTM)              (None, 5, 10)             840       
_________________________________________________________________
dropout_271 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_272 (LSTM)              (None, 10)                840       
_________________________________________________________________
dropout_272 (Dropout)        (None, 10)                0         
_________________________________________________________________
dense_90 (Dense)             (None, 1)               

In [879]:
# Summarize the model
model_aapl.summary()

Model: "sequential_91"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_273 (LSTM)              (None, 5, 10)             640       
_________________________________________________________________
dropout_273 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_274 (LSTM)              (None, 5, 10)             840       
_________________________________________________________________
dropout_274 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_275 (LSTM)              (None, 10)                840       
_________________________________________________________________
dropout_275 (Dropout)        (None, 10)                0         
_________________________________________________________________
dense_91 (Dense)             (None, 1)               

In [880]:
# Summarize the model
model_amzn.summary()

Model: "sequential_92"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_276 (LSTM)              (None, 5, 10)             640       
_________________________________________________________________
dropout_276 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_277 (LSTM)              (None, 5, 10)             840       
_________________________________________________________________
dropout_277 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_278 (LSTM)              (None, 10)                840       
_________________________________________________________________
dropout_278 (Dropout)        (None, 10)                0         
_________________________________________________________________
dense_92 (Dense)             (None, 1)               

In [881]:
# Summarize the model
model_nflx.summary()

Model: "sequential_93"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_279 (LSTM)              (None, 5, 10)             640       
_________________________________________________________________
dropout_279 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_280 (LSTM)              (None, 5, 10)             840       
_________________________________________________________________
dropout_280 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_281 (LSTM)              (None, 10)                840       
_________________________________________________________________
dropout_281 (Dropout)        (None, 10)                0         
_________________________________________________________________
dense_93 (Dense)             (None, 1)               

In [882]:
# Summarize the model
model_googl.summary()

Model: "sequential_94"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_282 (LSTM)              (None, 5, 10)             640       
_________________________________________________________________
dropout_282 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_283 (LSTM)              (None, 5, 10)             840       
_________________________________________________________________
dropout_283 (Dropout)        (None, 5, 10)             0         
_________________________________________________________________
lstm_284 (LSTM)              (None, 10)                840       
_________________________________________________________________
dropout_284 (Dropout)        (None, 10)                0         
_________________________________________________________________
dense_94 (Dense)             (None, 1)               

In [883]:
# Train the model
model_fb.fit(X_fb_train, y_fb_train, epochs=75, shuffle=False, batch_size=1, verbose=0)

In [884]:
# Train the model
model_aapl.fit(X_aapl_train, y_aapl_train, epochs=75, shuffle=False, batch_size=1, verbose=0)

In [885]:
# Train the model
model_amzn.fit(X_amzn_train, y_amzn_train, epochs=75, shuffle=False, batch_size=1, verbose=0)

In [886]:
# Train the model
model_nflx.fit(X_nflx_train, y_nflx_train, epochs=75, shuffle=False, batch_size=1, verbose=0)

In [887]:
# Train the model
model_googl.fit(X_googl_train, y_googl_train, epochs=75, shuffle=False, batch_size=1, verbose=0)

In [888]:
# Evaluate the model
model_fb.evaluate(X_fb_test, y_fb_test)

25/25 [==============================] - 1s 59ms/sample - loss: 0.0102


0.010196590796113014

In [889]:
# Evaluate the model
model_aapl.evaluate(X_aapl_test, y_aapl_test)

25/25 [==============================] - 1s 53ms/sample - loss: 0.0022


0.0022068589460104704

In [890]:
# Evaluate the model
model_amzn.evaluate(X_amzn_test, y_amzn_test)

25/25 [==============================] - 1s 50ms/sample - loss: 0.0052


0.005158394109457731

In [891]:
# Evaluate the model
model_nflx.evaluate(X_nflx_test, y_nflx_test)

25/25 [==============================] - 1s 58ms/sample - loss: 0.0157


0.015692103654146194

In [892]:
# Evaluate the model
model_googl.evaluate(X_googl_test, y_googl_test)

25/25 [==============================] - 2s 69ms/sample - loss: 0.0014


0.0014039096422493458

In [893]:
# Make some predictions
predicted_fb = model_fb.predict(X_fb_test)

In [894]:
# Make some predictions
predicted_aapl = model_aapl.predict(X_aapl_test)

In [895]:
# Make some predictions
predicted_amzn = model_amzn.predict(X_amzn_test)

In [896]:
# Make some predictions
predicted_nflx = model_nflx.predict(X_nflx_test)

In [897]:
# Make some predictions
predicted_googl = model_googl.predict(X_googl_test)

In [898]:
# Recover the original prices instead of the scaled version
predicted_prices_fb = scaler_fb.inverse_transform(predicted_fb)
predicted_prices_fb

array([[199.97733],
       [199.88638],
       [199.37389],
       [201.1826 ],
       [201.5875 ],
       [201.93845],
       [200.57426],
       [199.9589 ],
       [195.0114 ],
       [196.09135],
       [196.44724],
       [196.06781],
       [195.97737],
       [198.79588],
       [194.06003],
       [188.24414],
       [187.56113],
       [188.46562],
       [191.25471],
       [195.38423],
       [198.712  ],
       [200.02158],
       [200.60677],
       [202.34956],
       [203.00208]], dtype=float32)

In [899]:
# Recover the original prices instead of the scaled version
predicted_prices_aapl = scaler_aapl.inverse_transform(predicted_aapl)
predicted_prices_aapl

array([[263.38647],
       [263.66824],
       [264.61334],
       [265.3744 ],
       [265.4161 ],
       [265.30197],
       [265.62204],
       [265.8127 ],
       [264.45193],
       [265.20142],
       [267.11713],
       [267.64578],
       [269.00085],
       [270.25604],
       [271.02216],
       [272.21335],
       [272.42834],
       [273.67914],
       [274.4883 ],
       [274.90488],
       [275.08237],
       [275.10757],
       [275.31003],
       [276.09903],
       [277.24362]], dtype=float32)

In [900]:
# Recover the original prices instead of the scaled version
predicted_prices_amzn = scaler_amzn.inverse_transform(predicted_amzn)
predicted_prices_amzn

array([[1731.6522],
       [1731.7012],
       [1746.2722],
       [1773.2595],
       [1795.732 ],
       [1800.7444],
       [1802.5054],
       [1795.3169],
       [1777.8904],
       [1756.7373],
       [1745.9675],
       [1741.4015],
       [1736.5085],
       [1732.213 ],
       [1736.2854],
       [1738.381 ],
       [1746.8647],
       [1770.3776],
       [1784.9738],
       [1796.6606],
       [1799.0577],
       [1796.4852],
       [1789.9197],
       [1840.5356],
       [1890.9104]], dtype=float32)

In [901]:
# Recover the original prices instead of the scaled version
predicted_prices_nflx = scaler_nflx.inverse_transform(predicted_nflx)
predicted_prices_nflx

array([[308.46155],
       [312.82303],
       [316.46344],
       [318.63022],
       [324.11002],
       [330.38458],
       [331.76187],
       [327.95615],
       [320.53415],
       [314.84332],
       [315.39392],
       [314.40503],
       [306.5868 ],
       [297.5644 ],
       [293.5128 ],
       [294.12833],
       [296.96613],
       [302.4098 ],
       [308.86038],
       [319.12634],
       [331.36942],
       [343.44778],
       [351.3735 ],
       [355.46213],
       [356.01172]], dtype=float32)

In [902]:
# Recover the original prices instead of the scaled version
predicted_prices_googl = scaler_googl.inverse_transform(predicted_googl)
predicted_prices_googl

array([[1322.1488],
       [1318.5044],
       [1315.8634],
       [1321.826 ],
       [1326.3969],
       [1320.5151],
       [1303.852 ],
       [1305.1631],
       [1318.9689],
       [1332.8053],
       [1341.6161],
       [1338.9005],
       [1345.6863],
       [1348.6736],
       [1350.1942],
       [1342.6255],
       [1351.9706],
       [1346.571 ],
       [1350.761 ],
       [1351.6521],
       [1346.0134],
       [1349.9362],
       [1351.318 ],
       [1354.3912],
       [1352.5769]], dtype=float32)

In [903]:
real_prices_fb = scaler_fb.inverse_transform(y_fb_test.reshape(-1, 1))
real_prices_aapl = scaler_aapl.inverse_transform(y_aapl_test.reshape(-1, 1))
real_prices_amzn = scaler_amzn.inverse_transform(y_amzn_test.reshape(-1, 1))
real_prices_nflx = scaler_nflx.inverse_transform(y_nflx_test.reshape(-1, 1))
real_prices_googl = scaler_googl.inverse_transform(y_googl_test.reshape(-1, 1))

In [904]:
# Create a DataFrame of Real and Predicted values
fb_stocks = pd.DataFrame({
    "Real": real_prices_fb.ravel(),
    "Predicted": predicted_prices_fb.ravel()
})
fb_stocks.head(10)

Real   Predicted
0  198.88  199.977325
1  199.75  199.886383
2  198.80  199.373886
3  202.00  201.182602
4  201.66  201.587494
5  199.69  201.938446
6  198.83  200.574265
7  198.70  199.958893
8  199.37  195.011398
9  201.04  196.091354

In [905]:
# Create a DataFrame of Real and Predicted values
aapl_stocks = pd.DataFrame({
    "Real": real_prices_aapl.ravel(),
    "Predicted": predicted_prices_aapl.ravel()
})
aapl_stocks.head(10)

Real   Predicted
0  261.8400  263.386475
1  266.4200  263.668243
2  264.1000  264.613342
3  267.8999  265.374390
4  267.1800  265.416107
5  264.0900  265.301971
6  259.5200  265.622040
7  261.7400  265.812714
8  265.5800  264.451935
9  270.7000  265.201416

In [906]:
# Create a DataFrame of Real and Predicted values
amzn_stocks = pd.DataFrame({
    "Real": real_prices_amzn.ravel(),
    "Predicted": predicted_prices_amzn.ravel()
})
amzn_stocks.head(10)

Real    Predicted
0  1745.85  1731.652222
1  1773.69  1731.701172
2  1796.99  1746.272217
3  1818.23  1773.259521
4  1800.96  1795.732056
5  1781.61  1800.744385
6  1770.33  1802.505371
7  1760.48  1795.316895
8  1740.48  1777.890381
9  1751.59  1756.737305

In [907]:
# Create a DataFrame of Real and Predicted values
nflx_stocks = pd.DataFrame({
    "Real": real_prices_nflx.ravel(),
    "Predicted": predicted_prices_nflx.ravel()
})
nflx_stocks.head(10)

Real   Predicted
0  310.49  308.461548
1  315.68  312.823029
2  312.02  316.463440
3  315.93  318.630219
4  314.71  324.110016
5  310.02  330.384583
6  306.13  331.761871
7  304.28  327.956146
8  302.87  320.534149
9  307.27  314.843323

In [908]:
# Create a DataFrame of Real and Predicted values
googl_stocks = pd.DataFrame({
    "Real": real_prices_googl.ravel(),
    "Predicted": predicted_prices_googl.ravel()
})
googl_stocks.head(10)

Real    Predicted
0  1294.16  1322.148804
1  1305.65  1318.504395
2  1313.01  1315.863403
3  1312.46  1321.826050
4  1304.20  1326.396851
5  1288.86  1320.515137
6  1293.86  1303.852051
7  1318.30  1305.163086
8  1327.56  1318.968872
9  1339.41  1332.805298

In [909]:
# Plot the real vs predicted prices as a line chart
fb_stocks.hvplot(title = "fb")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [910]:
# Plot the real vs predicted prices as a line chart
aapl_stocks.hvplot(title = "aapl")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [911]:
# Plot the real vs predicted prices as a line chart
amzn_stocks.hvplot(title = "amzn")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [912]:
# Plot the real vs predicted prices as a line chart
nflx_stocks.hvplot(title = "nflx")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [913]:
# Plot the real vs predicted prices as a line chart
googl_stocks.hvplot(title = "googl")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [914]:
#model_fb.save('fb_lstm_model.h5')
#model_aapl.save('aapl_lstm_model.h5')
#model_amzn.save('amzn_lstm_model.h5')
#model_nflx.save('nflx_lstm_model.h5')
#model_googl.save('googl_lstm_model.h5')

# Predictions for Jan2020

In [1072]:
#Reading the .csv files with the Jan2020 Data

fb_csv = Path("../Resources/fb_data_Jan2020.csv")
fb_df = pd.read_csv(fb_csv)
fb_df['Date'] = pd.to_datetime(fb_df.Date).dt.date

aapl_csv = Path("../Resources/aapl_data_Jan2020.csv")
aapl_df = pd.read_csv(aapl_csv)
aapl_df['Date'] = pd.to_datetime(aapl_df.Date).dt.date

amzn_csv = Path("../Resources/amzn_data_Jan2020.csv")
amzn_df = pd.read_csv(amzn_csv)
amzn_df['Date'] = pd.to_datetime(amzn_df.Date).dt.date

nflx_csv = Path("../Resources/nflx_data_Jan2020.csv")
nflx_df = pd.read_csv(nflx_csv)
nflx_df['Date'] = pd.to_datetime(nflx_df.Date).dt.date

googl_csv = Path("../Resources/googl_data_Jan2020.csv")
googl_df = pd.read_csv(googl_csv)
googl_df['Date'] = pd.to_datetime(googl_df.Date).dt.date

dates = fb_df.Date.values
fb_df.set_index("Date", inplace = True)
aapl_df.set_index("Date", inplace = True)
amzn_df.set_index("Date", inplace = True)
nflx_df.set_index("Date", inplace = True)
googl_df.set_index("Date", inplace = True)

In [1073]:
fb_df = fb_df[["Close", "Volume", "Volatility", "sentiment", "RSI", "Open"]]
aapl_df = aapl_df[["Close", "Volume", "Volatility", "sentiment", "RSI", "Open"]]
amzn_df = amzn_df[["Close", "Volume", "Volatility", "sentiment", "RSI", "Open"]]
nflx_df = nflx_df[["Close", "Volume", "Volatility", "sentiment", "RSI", "Open"]]
googl_df = googl_df[["Close", "Volume", "Volatility", "sentiment", "RSI", "Open"]]

googl_df

Close    Volume  Volatility  sentiment       RSI      Open
Date                                                                     
2019-01-23  0.157435  0.109750    0.012810   0.942184  0.379153  0.119401
2019-01-24  0.175509  0.121857    0.005687   0.773885  0.398631  0.056748
2019-01-25  0.360976  0.049075    0.013523   0.863883  0.596044  0.225551
2019-01-28  0.123476  0.108721    0.031967   0.206057  0.246337  0.165634
2019-01-29  0.000000  0.036966    0.028076   0.094979  0.078047  0.035575
2019-01-30  0.348067  0.117574    0.064828   0.821937  0.465527  0.000000
2019-01-31  0.672650  0.298200    0.061234   1.000000  0.763302  0.484949
2019-02-01  0.610746  0.189376    0.010041   0.729194  0.672370  0.629699
2019-02-04  0.863097  0.595976    0.152880   0.673729  0.890515  0.598156
2019-02-05  1.000000  1.000000    0.244317   0.870841  1.000000  0.735417
2019-02-06  0.654454  0.411451    0.147031   0.596265  0.493523  1.000000
2019-02-07  0.416795  0.299379    0.037775   0.152218  0.192434  0.475875
2019-02-08  0.382984  0.051816    0.016729   0.668147  0.150716  0.234913
2019-02-11  0.396016  0.000000    0.003187   0.273082  0.165648  0.362667
2019-02-12  0.705539  0.234381    0.071024   0.543378  0.500601  0.467233
2019-02-13  0.695397  0.181688    0.024829   0.557035  0.485668  0.784531
2019-02-14  0.729206  0.053716    0.011511   0.152101  0.522597  0.668731
2019-02-15  0.603307  0.167984    0.065944   0.000000  0.321350  0.837678
2019-02-19  0.681434  0.010917    0.020271   0.646167  0.417349  0.548322
2019-02-20  0.626790  0.095026    0.024155   0.874982  0.325023  0.724615
2019-02-21  0.424049  0.215844    0.059480   0.854107  0.000000  0.579144
2019-02-22  0.573923  0.130935    0.023640   0.904997  0.211007  0.448365

In [1074]:
dates

array([datetime.date(2019, 1, 23), datetime.date(2019, 1, 24),
       datetime.date(2019, 1, 25), datetime.date(2019, 1, 28),
       datetime.date(2019, 1, 29), datetime.date(2019, 1, 30),
       datetime.date(2019, 1, 31), datetime.date(2019, 2, 1),
       datetime.date(2019, 2, 4), datetime.date(2019, 2, 5),
       datetime.date(2019, 2, 6), datetime.date(2019, 2, 7),
       datetime.date(2019, 2, 8), datetime.date(2019, 2, 11),
       datetime.date(2019, 2, 12), datetime.date(2019, 2, 13),
       datetime.date(2019, 2, 14), datetime.date(2019, 2, 15),
       datetime.date(2019, 2, 19), datetime.date(2019, 2, 20),
       datetime.date(2019, 2, 21), datetime.date(2019, 2, 22)],
      dtype=object)

In [1075]:
# Creating the features (X) and target (y) data using the window_data() function.
window_size = 5

feature_column = 0
target_column = 0

X_fb, y_fb = window_data(fb_df_scaled, window_size, feature_column, target_column)

X_aapl, y_aapl = window_data(aapl_df_scaled, window_size, feature_column, target_column)

X_amzn, y_amzn = window_data(amzn_df_scaled, window_size, feature_column, target_column)

X_nflx, y_nflx = window_data(nflx_df_scaled, window_size, feature_column, target_column)

X_googl, y_googl = window_data(googl_df_scaled, window_size, feature_column, target_column)

In [1076]:
# Evaluate the model
model_fb.evaluate(X_fb_test, y_fb_test)
model_aapl.evaluate(X_aapl_test, y_aapl_test)
model_amzn.evaluate(X_amzn_test, y_amzn_test)
model_nflx.evaluate(X_nflx_test, y_nflx_test)
model_googl.evaluate(X_googl_test, y_googl_test)

# Make some predictions
predicted_fb = model_fb.predict(X_fb_test)
predicted_aapl = model_aapl.predict(X_aapl_test)
predicted_amzn = model_amzn.predict(X_amzn_test)
predicted_nflx = model_nflx.predict(X_nflx_test)
predicted_googl = model_googl.predict(X_googl_test)

# Recover the original prices instead of the scaled version
predicted_prices_fb = scaler_fb.inverse_transform(predicted_fb)
predicted_prices_aapl = scaler_aapl.inverse_transform(predicted_aapl)
predicted_prices_amzn = scaler_amzn.inverse_transform(predicted_amzn)
predicted_prices_nflx = scaler_nflx.inverse_transform(predicted_nflx)
predicted_prices_googl = scaler_googl.inverse_transform(predicted_googl)


25/25 [==============================] - 0s 153us/sample - loss: 0.0014


In [1077]:
predicted_prices_fb

array([[199.97733],
       [199.88638],
       [199.37389],
       [201.1826 ],
       [201.5875 ],
       [201.93845],
       [200.57426],
       [199.9589 ],
       [195.0114 ],
       [196.09135],
       [196.44724],
       [196.06781],
       [195.97737],
       [198.79588],
       [194.06003],
       [188.24414],
       [187.56113],
       [188.46562],
       [191.25471],
       [195.38423],
       [198.712  ],
       [200.02158],
       [200.60677],
       [202.34956],
       [203.00208]], dtype=float32)

In [1078]:
predicted_prices_aapl

array([[263.38647],
       [263.66824],
       [264.61334],
       [265.3744 ],
       [265.4161 ],
       [265.30197],
       [265.62204],
       [265.8127 ],
       [264.45193],
       [265.20142],
       [267.11713],
       [267.64578],
       [269.00085],
       [270.25604],
       [271.02216],
       [272.21335],
       [272.42834],
       [273.67914],
       [274.4883 ],
       [274.90488],
       [275.08237],
       [275.10757],
       [275.31003],
       [276.09903],
       [277.24362]], dtype=float32)

In [1079]:
predicted_prices_amzn

array([[1731.6522],
       [1731.7012],
       [1746.2722],
       [1773.2595],
       [1795.732 ],
       [1800.7444],
       [1802.5054],
       [1795.3169],
       [1777.8904],
       [1756.7373],
       [1745.9675],
       [1741.4015],
       [1736.5085],
       [1732.213 ],
       [1736.2854],
       [1738.381 ],
       [1746.8647],
       [1770.3776],
       [1784.9738],
       [1796.6606],
       [1799.0577],
       [1796.4852],
       [1789.9197],
       [1840.5356],
       [1890.9104]], dtype=float32)

In [1080]:
predicted_prices_nflx

array([[308.46155],
       [312.82303],
       [316.46344],
       [318.63022],
       [324.11002],
       [330.38458],
       [331.76187],
       [327.95615],
       [320.53415],
       [314.84332],
       [315.39392],
       [314.40503],
       [306.5868 ],
       [297.5644 ],
       [293.5128 ],
       [294.12833],
       [296.96613],
       [302.4098 ],
       [308.86038],
       [319.12634],
       [331.36942],
       [343.44778],
       [351.3735 ],
       [355.46213],
       [356.01172]], dtype=float32)

In [1081]:
predicted_prices_googl

array([[1322.1488],
       [1318.5044],
       [1315.8634],
       [1321.826 ],
       [1326.3969],
       [1320.5151],
       [1303.852 ],
       [1305.1631],
       [1318.9689],
       [1332.8053],
       [1341.6161],
       [1338.9005],
       [1345.6863],
       [1348.6736],
       [1350.1942],
       [1342.6255],
       [1351.9706],
       [1346.571 ],
       [1350.761 ],
       [1351.6521],
       [1346.0134],
       [1349.9362],
       [1351.318 ],
       [1354.3912],
       [1352.5769]], dtype=float32)

In [1082]:
# Create a DataFrame of Real and Predicted values

predicted_prices = pd.DataFrame({
    "fb": predicted_prices_fb.ravel(),
    "aapl": predicted_prices_aapl.ravel(),
    "amzn": predicted_prices_amzn.ravel(),
    "nflx": predicted_prices_nflx.ravel(),
    "googl": predicted_prices_googl.ravel()
})

predicted_prices

fb        aapl         amzn        nflx        googl
0   199.977325  263.386475  1731.652222  308.461548  1322.148804
1   199.886383  263.668243  1731.701172  312.823029  1318.504395
2   199.373886  264.613342  1746.272217  316.463440  1315.863403
3   201.182602  265.374390  1773.259521  318.630219  1321.826050
4   201.587494  265.416107  1795.732056  324.110016  1326.396851
5   201.938446  265.301971  1800.744385  330.384583  1320.515137
6   200.574265  265.622040  1802.505371  331.761871  1303.852051
7   199.958893  265.812714  1795.316895  327.956146  1305.163086
8   195.011398  264.451935  1777.890381  320.534149  1318.968872
9   196.091354  265.201416  1756.737305  314.843323  1332.805298
10  196.447235  267.117126  1745.967529  315.393921  1341.616089
11  196.067810  267.645782  1741.401489  314.405029  1338.900513
12  195.977371  269.000854  1736.508545  306.586792  1345.686279
13  198.795883  270.256042  1732.213013  297.564392  1348.673584
14  194.060028  271.022156  1736.285400  293.512787  1350.194214
15  188.244141  272.213348  1738.380981  294.128326  1342.625488
16  187.561127  272.428345  1746.864746  296.966125  1351.970581
17  188.465622  273.679138  1770.377563  302.409790  1346.571045
18  191.254715  274.488312  1784.973755  308.860382  1350.760986
19  195.384232  274.904877  1796.660645  319.126343  1351.652100
20  198.712006  275.082367  1799.057739  331.369415  1346.013428
21  200.021576  275.107574  1796.485229  343.447784  1349.936157
22  200.606766  275.310028  1789.919678  351.373505  1351.317993
23  202.349564  276.099030  1840.535645  355.462128  1354.391235
24  203.002075  277.243622  1890.910400  356.011719  1352.576904

In [1083]:
predicted_prices["Date"] = pd.to_datetime("2020-1-1").date()
for i in range (len(dates)):
    predicted_prices.Date.iloc[i] = dates[i]
predicted_prices

/Users/andresmejia/opt/anaconda3/envs/vizenv/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


fb        aapl         amzn        nflx        googl        Date
0   199.977325  263.386475  1731.652222  308.461548  1322.148804  2019-01-23
1   199.886383  263.668243  1731.701172  312.823029  1318.504395  2019-01-24
2   199.373886  264.613342  1746.272217  316.463440  1315.863403  2019-01-25
3   201.182602  265.374390  1773.259521  318.630219  1321.826050  2019-01-28
4   201.587494  265.416107  1795.732056  324.110016  1326.396851  2019-01-29
5   201.938446  265.301971  1800.744385  330.384583  1320.515137  2019-01-30
6   200.574265  265.622040  1802.505371  331.761871  1303.852051  2019-01-31
7   199.958893  265.812714  1795.316895  327.956146  1305.163086  2019-02-01
8   195.011398  264.451935  1777.890381  320.534149  1318.968872  2019-02-04
9   196.091354  265.201416  1756.737305  314.843323  1332.805298  2019-02-05
10  196.447235  267.117126  1745.967529  315.393921  1341.616089  2019-02-06
11  196.067810  267.645782  1741.401489  314.405029  1338.900513  2019-02-07
12  195.977371  269.000854  1736.508545  306.586792  1345.686279  2019-02-08
13  198.795883  270.256042  1732.213013  297.564392  1348.673584  2019-02-11
14  194.060028  271.022156  1736.285400  293.512787  1350.194214  2019-02-12
15  188.244141  272.213348  1738.380981  294.128326  1342.625488  2019-02-13
16  187.561127  272.428345  1746.864746  296.966125  1351.970581  2019-02-14
17  188.465622  273.679138  1770.377563  302.409790  1346.571045  2019-02-15
18  191.254715  274.488312  1784.973755  308.860382  1350.760986  2019-02-19
19  195.384232  274.904877  1796.660645  319.126343  1351.652100  2019-02-20
20  198.712006  275.082367  1799.057739  331.369415  1346.013428  2019-02-21
21  200.021576  275.107574  1796.485229  343.447784  1349.936157  2019-02-22
22  200.606766  275.310028  1789.919678  351.373505  1351.317993  2020-01-01
23  202.349564  276.099030  1840.535645  355.462128  1354.391235  2020-01-01
24  203.002075  277.243622  1890.910400  356.011719  1352.576904  2020-01-01

In [1088]:
predicted_prices = predicted_prices[["Date", "fb", "aapl", "amzn", "nflx", "googl"]]
predicted_prices

Date          fb        aapl         amzn        nflx        googl
0   2019-01-23  199.977325  263.386475  1731.652222  308.461548  1322.148804
1   2019-01-24  199.886383  263.668243  1731.701172  312.823029  1318.504395
2   2019-01-25  199.373886  264.613342  1746.272217  316.463440  1315.863403
3   2019-01-28  201.182602  265.374390  1773.259521  318.630219  1321.826050
4   2019-01-29  201.587494  265.416107  1795.732056  324.110016  1326.396851
5   2019-01-30  201.938446  265.301971  1800.744385  330.384583  1320.515137
6   2019-01-31  200.574265  265.622040  1802.505371  331.761871  1303.852051
7   2019-02-01  199.958893  265.812714  1795.316895  327.956146  1305.163086
8   2019-02-04  195.011398  264.451935  1777.890381  320.534149  1318.968872
9   2019-02-05  196.091354  265.201416  1756.737305  314.843323  1332.805298
10  2019-02-06  196.447235  267.117126  1745.967529  315.393921  1341.616089
11  2019-02-07  196.067810  267.645782  1741.401489  314.405029  1338.900513
12  2019-02-08  195.977371  269.000854  1736.508545  306.586792  1345.686279
13  2019-02-11  198.795883  270.256042  1732.213013  297.564392  1348.673584
14  2019-02-12  194.060028  271.022156  1736.285400  293.512787  1350.194214
15  2019-02-13  188.244141  272.213348  1738.380981  294.128326  1342.625488
16  2019-02-14  187.561127  272.428345  1746.864746  296.966125  1351.970581
17  2019-02-15  188.465622  273.679138  1770.377563  302.409790  1346.571045
18  2019-02-19  191.254715  274.488312  1784.973755  308.860382  1350.760986
19  2019-02-20  195.384232  274.904877  1796.660645  319.126343  1351.652100
20  2019-02-21  198.712006  275.082367  1799.057739  331.369415  1346.013428
21  2019-02-22  200.021576  275.107574  1796.485229  343.447784  1349.936157
22  2020-01-01  200.606766  275.310028  1789.919678  351.373505  1351.317993
23  2020-01-01  202.349564  276.099030  1840.535645  355.462128  1354.391235
24  2020-01-01  203.002075  277.243622  1890.910400  356.011719  1352.576904

In [1089]:
#Saving data to .csv files
predicted_prices.loc[:len(dates)-1].to_csv("../Resources/PREDICTED_PRICES_JAN_2020.csv", encoding='utf-8', index = False)