In [243]:
# Initial imports
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn import preprocessing
import hvplot.pandas

%matplotlib inline

In [244]:
# Set the random seed for reproducibility
# Note: This is used for model prototyping, but it is good practice to comment this out and run multiple experiments to evaluate your model.
from numpy.random import seed

seed(1)
from tensorflow import random

random.set_seed(2)

In [245]:
#Reading the .csv files

fb_csv = Path("../Resources/fb_data.csv")
fb_df = pd.read_csv(fb_csv)
fb_df['Date'] = pd.to_datetime(fb_df.Date).dt.date

aapl_csv = Path("../Resources/aapl_data.csv")
aapl_df = pd.read_csv(aapl_csv)
aapl_df['Date'] = pd.to_datetime(aapl_df.Date).dt.date

amzn_csv = Path("../Resources/amzn_data.csv")
amzn_df = pd.read_csv(amzn_csv)
amzn_df['Date'] = pd.to_datetime(amzn_df.Date).dt.date

nflx_csv = Path("../Resources/nflx_data.csv")
nflx_df = pd.read_csv(nflx_csv)
nflx_df['Date'] = pd.to_datetime(nflx_df.Date).dt.date

googl_csv = Path("../Resources/googl_data.csv")
googl_df = pd.read_csv(googl_csv)
googl_df['Date'] = pd.to_datetime(googl_df.Date).dt.date

fb_df.set_index("Date", inplace = True)
aapl_df.set_index("Date", inplace = True)
amzn_df.set_index("Date", inplace = True)
nflx_df.set_index("Date", inplace = True)
googl_df.set_index("Date", inplace = True)

In [246]:
#fb_df = fb_df.drop(columns=["High", "Low"])
fb_df_scaled = fb_df

#aapl_df = aapl_df.drop(columns=["High", "Low"])
aapl_df_scaled = aapl_df

#amzn_df = amzn_df.drop(columns=["High", "Low"])
amzn_df_scaled = amzn_df

#nflx_df = nflx_df.drop(columns=["High", "Low"])
nflx_df_scaled = nflx_df

#googl_df = googl_df.drop(columns=["High", "Low"])
googl_df_scaled = googl_df

In [247]:
#Scaling all the columns

x = fb_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["Open0_1"] = x_scaled

x = fb_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["High0_1"] = x_scaled

x = fb_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["Low0_1"] = x_scaled

x = fb_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["Volume"] = x_scaled

x = fb_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["sentiment"] = x_scaled

x = fb_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
fb_df_scaled["RSI"] = x_scaled

fb_df_scaled = fb_df_scaled.drop(columns=["Open", "High", "Low"])
#fb_df_scaled.dropna(inplace=True)
fb_df_scaled=fb_df_scaled.fillna(0)

x = aapl_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["Open0_1"] = x_scaled

x = aapl_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["High0_1"] = x_scaled

x = aapl_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["Low0_1"] = x_scaled

x = aapl_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["Volume"] = x_scaled
aapl_df_scaled

x = aapl_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["sentiment"] = x_scaled
aapl_df_scaled

x = aapl_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
aapl_df_scaled["RSI"] = x_scaled

aapl_df_scaled = aapl_df_scaled.drop(columns=["Open", "High", "Low"])
#aapl_df_scaled.dropna(inplace=True)
aapl_df_scaled=aapl_df_scaled.fillna(0)

x = amzn_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["Open0_1"] = x_scaled

x = amzn_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["High0_1"] = x_scaled

x = amzn_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["Low0_1"] = x_scaled

x = amzn_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["Volume"] = x_scaled

x = amzn_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["sentiment"] = x_scaled

x = amzn_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
amzn_df_scaled["RSI"] = x_scaled

amzn_df_scaled = amzn_df_scaled.drop(columns=["Open", "High", "Low"])
#amzn_df_scaled.dropna(inplace=True)
amzn_df_scaled=amzn_df_scaled.fillna(0)

x = nflx_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["Open0_1"] = x_scaled

x = nflx_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["High0_1"] = x_scaled

x = nflx_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["Low0_1"] = x_scaled

x = nflx_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["Volume"] = x_scaled

x = nflx_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["sentiment"] = x_scaled

x = nflx_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
nflx_df_scaled["RSI"] = x_scaled

nflx_df_scaled = nflx_df_scaled.drop(columns=["Open", "High", "Low"])
#nflx_df_scaled.dropna(inplace=True)
nflx_df_scaled=nflx_df_scaled.fillna(0)

x = googl_df_scaled.Open.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["Open0_1"] = x_scaled

x = googl_df_scaled.High.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["High0_1"] = x_scaled

x = googl_df_scaled.Low.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["Low0_1"] = x_scaled

x = googl_df_scaled.Volume.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["Volume"] = x_scaled

x = googl_df_scaled.sentiment.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["sentiment"] = x_scaled

x = googl_df_scaled.RSI.values
x = x.reshape(-1,1)
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
x_scaled
googl_df_scaled["RSI"] = x_scaled

googl_df_scaled = googl_df_scaled.drop(columns=["Open", "High", "Low"])
#googl_df_scaled.dropna(inplace=True)
googl_df_scaled=googl_df_scaled.fillna(0)
googl_df_scaled

Close    Volume  Volatility  sentiment       RSI   Open0_1  \
Date                                                                        
2019-01-02  1053.240  0.152773    0.279226   0.262816  0.000000  0.000000   
2019-01-03  1026.505  0.189410    0.297727   0.321999  0.000000  0.069685   
2019-01-04  1076.550  0.234292    0.498923   0.419047  0.000000  0.042844   
2019-01-07  1076.010  0.248849    0.073502   0.524146  0.000000  0.159650   
2019-01-08  1085.510  0.163034    0.007682   0.760071  0.000000  0.170932   
...              ...       ...         ...        ...       ...       ...   
2019-12-24  1344.740  0.015894    0.025493   0.372467  0.663397  0.959056   
2019-12-26  1362.160  0.074121    0.113546   0.523969  0.790973  0.948189   
2019-12-27  1354.640  0.063306    0.063423   0.526298  0.701485  1.000000   
2019-12-30  1340.470  0.057970    0.107363   0.435962  0.554641  0.978652   
2019-12-31  1338.120  0.038471    0.012810   0.698379  0.532288  0.916241   

             High0_1    Low0_1  
Date                            
2019-01-02  0.034030  0.008786  
2019-01-03  0.051282  0.000000  
2019-01-04  0.094616  0.043825  
2019-01-07  0.103132  0.121798  
2019-01-08  0.136721  0.139064  
...              ...       ...  
2019-12-24  0.952503  0.973278  
2019-12-26  0.987794  0.977346  
2019-12-27  1.000000  1.000000  
2019-12-30  0.968240  0.954133  
2019-12-31  0.916706  0.936878  

[252 rows x 8 columns]

In [248]:
def window_data(df, window, feature_col_number, target_col_number):
    """
    This function accepts the column number for the features (X) and the target (y).
    It chunks the data up with a rolling window of Xt - window to predict Xt.
    It returns two numpy arrays of X and y.
    """
    X = []
    y = []
    for i in range(len(df) - window - 1):
        features = df.iloc[i : (i + window), 1:6].values
        X.append(features)
        target = df.iloc[(i + window), target_col_number]
        y.append(target)
    return np.array(X), np.array(y).reshape(-1, 1)

In [249]:
# Creating the features (X) and target (y) data using the window_data() function.
window_size = 5

feature_column = 0
target_column = 0
X_fb, y_fb = window_data(fb_df_scaled, window_size, feature_column, target_column)
#print (f"X_fb sample values:\n{X_fb[:5]} \n")
#print (f"y_fb sample values:\n{y_fb[:5]}")

X_aapl, y_aapl = window_data(aapl_df_scaled, window_size, feature_column, target_column)
#print (f"X_aapl sample values:\n{X_aapl[:5]} \n")
#print (f"y_aapl sample values:\n{y_aapl[:5]}")

X_amzn, y_amzn = window_data(amzn_df_scaled, window_size, feature_column, target_column)
#print (f"X_amzn sample values:\n{X_amzn[:5]} \n")
#print (f"y_amzn sample values:\n{y_amzn[:5]}")

X_nflx, y_nflx = window_data(nflx_df_scaled, window_size, feature_column, target_column)
#print (f"X_nflx sample values:\n{X_nflx[:5]} \n")
#print (f"y_nflx sample values:\n{y_nflx[:5]}")

X_googl, y_googl = window_data(googl_df_scaled, window_size, feature_column, target_column)
#print (f"X_googl sample values:\n{X_googl[:5]} \n")
#print (f"y_googl sample values:\n{y_googl[:5]}")


In [250]:
# Use 90% of the data for training and the remainder for testing
split = int(0.90 * len(X_fb))
X_fb_train = X_fb[: split - 1]
X_fb_test = X_fb[split:]
y_fb_train = y_fb[: split - 1]
y_fb_test = y_fb[split:]

X_aapl_train = X_aapl[: split - 1]
X_aapl_test = X_aapl[split:]
y_aapl_train = y_aapl[: split - 1]
y_aapl_test = y_aapl[split:]

X_amzn_train = X_amzn[: split - 1]
X_amzn_test = X_amzn[split:]
y_amzn_train = y_amzn[: split - 1]
y_amzn_test = y_amzn[split:]

X_nflx_train = X_nflx[: split - 1]
X_nflx_test = X_nflx[split:]
y_nflx_train = y_nflx[: split - 1]
y_nflx_test = y_nflx[split:]

X_googl_train = X_googl[: split - 1]
X_googl_test = X_googl[split:]
y_googl_train = y_googl[: split - 1]
y_googl_test = y_googl[split:]


In [251]:
# Use the MinMaxScaler to scale data between 0 and 1.
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(y_fb)
y_fb_train = scaler.transform(y_fb_train)
y_fb_test = scaler.transform(y_fb_test)

scaler.fit(y_aapl)
y_aapl_train = scaler.transform(y_aapl_train)
y_aapl_test = scaler.transform(y_aapl_test)

scaler.fit(y_amzn)
y_amzn_train = scaler.transform(y_amzn_train)
y_amzn_test = scaler.transform(y_amzn_test)

scaler.fit(y_nflx)
y_nflx_train = scaler.transform(y_nflx_train)
y_nflx_test = scaler.transform(y_nflx_test)

scaler.fit(y_googl)
y_googl_train = scaler.transform(y_googl_train)
y_googl_test = scaler.transform(y_googl_test)


In [252]:
X_fb_train = X_fb_train.reshape((X_fb_train.shape[0], X_fb_train.shape[1], 5))
X_fb_test = X_fb_test.reshape((X_fb_test.shape[0], X_fb_test.shape[1], 5))
#print (f"X_train sample values:\n{X_fb_train[:5]} \n")
#print (f"X_test sample values:\n{X_fb_test[:5]}")

X_aapl_train = X_aapl_train.reshape((X_aapl_train.shape[0], X_aapl_train.shape[1], 5))
X_aapl_test = X_aapl_test.reshape((X_aapl_test.shape[0], X_aapl_test.shape[1], 5))
#print (f"X_train sample values:\n{X_aapl_train[:5]} \n")
#print (f"X_test sample values:\n{X_aapl_test[:5]}")

X_amzn_train = X_amzn_train.reshape((X_amzn_train.shape[0], X_amzn_train.shape[1], 5))
X_amzn_test = X_amzn_test.reshape((X_amzn_test.shape[0], X_amzn_test.shape[1], 5))
#print (f"X_train sample values:\n{X_amzn_train[:5]} \n")
#print (f"X_test sample values:\n{X_amzn_test[:5]}")

X_nflx_train = X_nflx_train.reshape((X_nflx_train.shape[0], X_nflx_train.shape[1], 5))
X_nflx_test = X_nflx_test.reshape((X_nflx_test.shape[0], X_nflx_test.shape[1], 5))
#print (f"X_train sample values:\n{X_nflx_train[:5]} \n")
#print (f"X_test sample values:\n{X_nflx_test[:5]}")

X_googl_train = X_googl_train.reshape((X_googl_train.shape[0], X_googl_train.shape[1], 5))
X_googl_test = X_googl_test.reshape((X_googl_test.shape[0], X_googl_test.shape[1], 5))
print (f"X_train sample values:\n{X_googl_train[:5]} \n")
print (f"X_test sample values:\n{X_googl_test[:5]}")


X_train sample values:
[[[0.15277328 0.27922631 0.26281589 0.         0.        ]
  [0.18941024 0.29772725 0.32199852 0.         0.06968527]
  [0.2342916  0.49892313 0.4190467  0.         0.04284442]
  [0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.76007102 0.         0.1709323 ]]

 [[0.18941024 0.29772725 0.32199852 0.         0.06968527]
  [0.2342916  0.49892313 0.4190467  0.         0.04284442]
  [0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.76007102 0.         0.1709323 ]
  [0.11760959 0.04333437 0.57968104 0.         0.18049287]]

 [[0.2342916  0.49892313 0.4190467  0.         0.04284442]
  [0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.76007102 0.         0.1709323 ]
  [0.11760959 0.04333437 0.57968104 0.         0.18049287]
  [0.10625191 0.02998816 0.11774981 0.         0.14174584]]

 [[0.24884939 0.07350218 0.52414609 0.         0.15964964]
  [0.16303446 0.00768151 0.

In [253]:
# Import required Keras modules
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [254]:
# Define the LSTM RNN model.
model_fb = Sequential()

number_units = 10
dropout_fraction = 0.2

# Layer 1
model_fb.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_fb_train.shape[1], 5))
    )
model_fb.add(Dropout(dropout_fraction))
# Layer 2
model_fb.add(LSTM(units=number_units, return_sequences=True))
model_fb.add(Dropout(dropout_fraction))
# Layer 3
model_fb.add(LSTM(units=number_units))
model_fb.add(Dropout(dropout_fraction))
# Output layer
model_fb.add(Dense(1))

model_aapl = Sequential()

# Layer 1
model_aapl.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_aapl_train.shape[1], 5))
    )
model_aapl.add(Dropout(dropout_fraction))
# Layer 2
model_aapl.add(LSTM(units=number_units, return_sequences=True))
model_aapl.add(Dropout(dropout_fraction))
# Layer 3
model_aapl.add(LSTM(units=number_units))
model_aapl.add(Dropout(dropout_fraction))
# Output layer
model_aapl.add(Dense(1))

model_amzn = Sequential()

# Layer 1
model_amzn.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_amzn_train.shape[1], 5))
    )
model_amzn.add(Dropout(dropout_fraction))
# Layer 2
model_amzn.add(LSTM(units=number_units, return_sequences=True))
model_amzn.add(Dropout(dropout_fraction))
# Layer 3
model_amzn.add(LSTM(units=number_units))
model_amzn.add(Dropout(dropout_fraction))
# Output layer
model_amzn.add(Dense(1))

model_nflx = Sequential()

# Layer 1
model_nflx.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_nflx_train.shape[1], 5))
    )
model_nflx.add(Dropout(dropout_fraction))
# Layer 2
model_nflx.add(LSTM(units=number_units, return_sequences=True))
model_nflx.add(Dropout(dropout_fraction))
# Layer 3
model_nflx.add(LSTM(units=number_units))
model_nflx.add(Dropout(dropout_fraction))
# Output layer
model_nflx.add(Dense(1))

model_googl = Sequential()

# Layer 1
model_googl.add(LSTM(
    units=number_units,
    return_sequences=True,
    input_shape=(X_googl_train.shape[1], 5))
    )
model_googl.add(Dropout(dropout_fraction))
# Layer 2
model_googl.add(LSTM(units=number_units, return_sequences=True))
model_googl.add(Dropout(dropout_fraction))
# Layer 3
model_googl.add(LSTM(units=number_units))
model_googl.add(Dropout(dropout_fraction))
# Output layer
model_googl.add(Dense(1))


In [255]:
# Compile the model
model_fb.compile(optimizer="adam", loss="mean_squared_error")
model_aapl.compile(optimizer="adam", loss="mean_squared_error")
model_amzn.compile(optimizer="adam", loss="mean_squared_error")
model_nflx.compile(optimizer="adam", loss="mean_squared_error")
model_googl.compile(optimizer="adam", loss="mean_squared_error")

In [256]:
# Summarize the model
model_fb.summary()

Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_75 (LSTM)               (None, 5, 10)             640       
_________________________________________________________________
dropout_75 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_76 (LSTM)               (None, 5, 10)             840       
_________________________________________________________________
dropout_76 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_77 (LSTM)               (None, 10)                840       
_________________________________________________________________
dropout_77 (Dropout)         (None, 10)                0         
_________________________________________________________________
dense_25 (Dense)             (None, 1)               

In [257]:
# Summarize the model
model_aapl.summary()

Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_78 (LSTM)               (None, 5, 10)             640       
_________________________________________________________________
dropout_78 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_79 (LSTM)               (None, 5, 10)             840       
_________________________________________________________________
dropout_79 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_80 (LSTM)               (None, 10)                840       
_________________________________________________________________
dropout_80 (Dropout)         (None, 10)                0         
_________________________________________________________________
dense_26 (Dense)             (None, 1)               

In [258]:
# Summarize the model
model_amzn.summary()

Model: "sequential_27"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_81 (LSTM)               (None, 5, 10)             640       
_________________________________________________________________
dropout_81 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_82 (LSTM)               (None, 5, 10)             840       
_________________________________________________________________
dropout_82 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_83 (LSTM)               (None, 10)                840       
_________________________________________________________________
dropout_83 (Dropout)         (None, 10)                0         
_________________________________________________________________
dense_27 (Dense)             (None, 1)               

In [259]:
# Summarize the model
model_nflx.summary()

Model: "sequential_28"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_84 (LSTM)               (None, 5, 10)             640       
_________________________________________________________________
dropout_84 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_85 (LSTM)               (None, 5, 10)             840       
_________________________________________________________________
dropout_85 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_86 (LSTM)               (None, 10)                840       
_________________________________________________________________
dropout_86 (Dropout)         (None, 10)                0         
_________________________________________________________________
dense_28 (Dense)             (None, 1)               

In [260]:
# Summarize the model
model_googl.summary()

Model: "sequential_29"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_87 (LSTM)               (None, 5, 10)             640       
_________________________________________________________________
dropout_87 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_88 (LSTM)               (None, 5, 10)             840       
_________________________________________________________________
dropout_88 (Dropout)         (None, 5, 10)             0         
_________________________________________________________________
lstm_89 (LSTM)               (None, 10)                840       
_________________________________________________________________
dropout_89 (Dropout)         (None, 10)                0         
_________________________________________________________________
dense_29 (Dense)             (None, 1)               

In [261]:
# Train the model
model_fb.fit(X_fb_train, y_fb_train, epochs=75, shuffle=False, batch_size=1, verbose=2)

Train on 220 samples
Epoch 1/75
220/220 - 4s - loss: 0.0265
Epoch 2/75
220/220 - 1s - loss: 0.0439
Epoch 3/75
220/220 - 1s - loss: 0.0318
Epoch 4/75
220/220 - 1s - loss: 0.0287
Epoch 5/75
220/220 - 1s - loss: 0.0263
Epoch 6/75
220/220 - 1s - loss: 0.0258
Epoch 7/75
220/220 - 1s - loss: 0.0231
Epoch 8/75
220/220 - 1s - loss: 0.0217
Epoch 9/75
220/220 - 1s - loss: 0.0212
Epoch 10/75
220/220 - 1s - loss: 0.0191
Epoch 11/75
220/220 - 1s - loss: 0.0187
Epoch 12/75
220/220 - 1s - loss: 0.0176
Epoch 13/75
220/220 - 1s - loss: 0.0171
Epoch 14/75
220/220 - 1s - loss: 0.0161
Epoch 15/75
220/220 - 1s - loss: 0.0163
Epoch 16/75
220/220 - 1s - loss: 0.0159
Epoch 17/75
220/220 - 1s - loss: 0.0136
Epoch 18/75
220/220 - 1s - loss: 0.0135
Epoch 19/75
220/220 - 1s - loss: 0.0141
Epoch 20/75
220/220 - 1s - loss: 0.0140
Epoch 21/75
220/220 - 1s - loss: 0.0156
Epoch 22/75
220/220 - 1s - loss: 0.0109
Epoch 23/75
220/220 - 1s - loss: 0.0114
Epoch 24/75
220/220 - 1s - loss: 0.0111
Epoch 25/75
220/220 - 1s - l

In [262]:
# Train the model
model_aapl.fit(X_aapl_train, y_aapl_train, epochs=75, shuffle=False, batch_size=1, verbose=2)

Train on 220 samples
Epoch 1/75
220/220 - 3s - loss: 0.0076
Epoch 2/75
220/220 - 1s - loss: 0.0212
Epoch 3/75
220/220 - 1s - loss: 0.0161
Epoch 4/75
220/220 - 1s - loss: 0.0126
Epoch 5/75
220/220 - 1s - loss: 0.0129
Epoch 6/75
220/220 - 1s - loss: 0.0099
Epoch 7/75
220/220 - 1s - loss: 0.0069
Epoch 8/75
220/220 - 1s - loss: 0.0082
Epoch 9/75
220/220 - 1s - loss: 0.0076
Epoch 10/75
220/220 - 1s - loss: 0.0067
Epoch 11/75
220/220 - 1s - loss: 0.0060
Epoch 12/75
220/220 - 1s - loss: 0.0058
Epoch 13/75
220/220 - 1s - loss: 0.0054
Epoch 14/75
220/220 - 1s - loss: 0.0055
Epoch 15/75
220/220 - 1s - loss: 0.0047
Epoch 16/75
220/220 - 1s - loss: 0.0047
Epoch 17/75
220/220 - 1s - loss: 0.0050
Epoch 18/75
220/220 - 1s - loss: 0.0041
Epoch 19/75
220/220 - 1s - loss: 0.0053
Epoch 20/75
220/220 - 1s - loss: 0.0041
Epoch 21/75
220/220 - 1s - loss: 0.0043
Epoch 22/75
220/220 - 1s - loss: 0.0037
Epoch 23/75
220/220 - 1s - loss: 0.0033
Epoch 24/75
220/220 - 1s - loss: 0.0037
Epoch 25/75
220/220 - 1s - l

In [263]:
# Train the model
model_amzn.fit(X_amzn_train, y_amzn_train, epochs=75, shuffle=False, batch_size=1, verbose=2)

Train on 220 samples
Epoch 1/75
220/220 - 4s - loss: 0.0423
Epoch 2/75
220/220 - 1s - loss: 0.0385
Epoch 3/75
220/220 - 1s - loss: 0.0340
Epoch 4/75
220/220 - 1s - loss: 0.0257
Epoch 5/75
220/220 - 1s - loss: 0.0313
Epoch 6/75
220/220 - 1s - loss: 0.0275
Epoch 7/75
220/220 - 1s - loss: 0.0240
Epoch 8/75
220/220 - 1s - loss: 0.0260
Epoch 9/75
220/220 - 1s - loss: 0.0276
Epoch 10/75
220/220 - 1s - loss: 0.0247
Epoch 11/75
220/220 - 1s - loss: 0.0231
Epoch 12/75
220/220 - 1s - loss: 0.0227
Epoch 13/75
220/220 - 1s - loss: 0.0233
Epoch 14/75
220/220 - 1s - loss: 0.0222
Epoch 15/75
220/220 - 1s - loss: 0.0219
Epoch 16/75
220/220 - 1s - loss: 0.0208
Epoch 17/75
220/220 - 1s - loss: 0.0192
Epoch 18/75
220/220 - 1s - loss: 0.0178
Epoch 19/75
220/220 - 1s - loss: 0.0185
Epoch 20/75
220/220 - 1s - loss: 0.0199
Epoch 21/75
220/220 - 1s - loss: 0.0171
Epoch 22/75
220/220 - 1s - loss: 0.0155
Epoch 23/75
220/220 - 1s - loss: 0.0162
Epoch 24/75
220/220 - 1s - loss: 0.0162
Epoch 25/75
220/220 - 1s - l

In [264]:
# Train the model
model_nflx.fit(X_nflx_train, y_nflx_train, epochs=75, shuffle=False, batch_size=1, verbose=2)

Train on 220 samples
Epoch 1/75
220/220 - 6s - loss: 0.0933
Epoch 2/75
220/220 - 1s - loss: 0.0379
Epoch 3/75
220/220 - 1s - loss: 0.0397
Epoch 4/75
220/220 - 1s - loss: 0.0368
Epoch 5/75
220/220 - 1s - loss: 0.0372
Epoch 6/75
220/220 - 1s - loss: 0.0380
Epoch 7/75
220/220 - 1s - loss: 0.0365
Epoch 8/75
220/220 - 1s - loss: 0.0370
Epoch 9/75
220/220 - 1s - loss: 0.0319
Epoch 10/75
220/220 - 1s - loss: 0.0302
Epoch 11/75
220/220 - 1s - loss: 0.0251
Epoch 12/75
220/220 - 1s - loss: 0.0255
Epoch 13/75
220/220 - 1s - loss: 0.0245
Epoch 14/75
220/220 - 1s - loss: 0.0244
Epoch 15/75
220/220 - 1s - loss: 0.0224
Epoch 16/75
220/220 - 1s - loss: 0.0208
Epoch 17/75
220/220 - 1s - loss: 0.0202
Epoch 18/75
220/220 - 1s - loss: 0.0201
Epoch 19/75
220/220 - 1s - loss: 0.0187
Epoch 20/75
220/220 - 1s - loss: 0.0183
Epoch 21/75
220/220 - 1s - loss: 0.0169
Epoch 22/75
220/220 - 1s - loss: 0.0162
Epoch 23/75
220/220 - 1s - loss: 0.0150
Epoch 24/75
220/220 - 1s - loss: 0.0154
Epoch 25/75
220/220 - 1s - l

In [265]:
# Train the model
model_googl.fit(X_googl_train, y_googl_train, epochs=75, shuffle=False, batch_size=1, verbose=2)

Train on 220 samples
Epoch 1/75
220/220 - 4s - loss: 0.0254
Epoch 2/75
220/220 - 1s - loss: 0.0357
Epoch 3/75
220/220 - 1s - loss: 0.0274
Epoch 4/75
220/220 - 1s - loss: 0.0235
Epoch 5/75
220/220 - 1s - loss: 0.0246
Epoch 6/75
220/220 - 1s - loss: 0.0210
Epoch 7/75
220/220 - 1s - loss: 0.0164
Epoch 8/75
220/220 - 1s - loss: 0.0164
Epoch 9/75
220/220 - 1s - loss: 0.0160
Epoch 10/75
220/220 - 1s - loss: 0.0134
Epoch 11/75
220/220 - 1s - loss: 0.0123
Epoch 12/75
220/220 - 1s - loss: 0.0125
Epoch 13/75
220/220 - 1s - loss: 0.0125
Epoch 14/75
220/220 - 1s - loss: 0.0125
Epoch 15/75
220/220 - 1s - loss: 0.0111
Epoch 16/75
220/220 - 1s - loss: 0.0097
Epoch 17/75
220/220 - 1s - loss: 0.0100
Epoch 18/75
220/220 - 1s - loss: 0.0091
Epoch 19/75
220/220 - 1s - loss: 0.0111
Epoch 20/75
220/220 - 1s - loss: 0.0092
Epoch 21/75
220/220 - 1s - loss: 0.0092
Epoch 22/75
220/220 - 1s - loss: 0.0089
Epoch 23/75
220/220 - 1s - loss: 0.0088
Epoch 24/75
220/220 - 1s - loss: 0.0088
Epoch 25/75
220/220 - 1s - l

In [266]:
# Evaluate the model
model_fb.evaluate(X_fb_test, y_fb_test)

25/25 [==============================] - 1s 30ms/sample - loss: 0.0089


0.008852058090269566

In [267]:
# Evaluate the model
model_aapl.evaluate(X_aapl_test, y_aapl_test)

25/25 [==============================] - 1s 28ms/sample - loss: 0.0015


0.0015319216763600707

In [268]:
# Evaluate the model
model_amzn.evaluate(X_amzn_test, y_amzn_test)

25/25 [==============================] - 1s 28ms/sample - loss: 0.0065


0.006483172997832298

In [269]:
# Evaluate the model
model_nflx.evaluate(X_nflx_test, y_nflx_test)

25/25 [==============================] - 1s 28ms/sample - loss: 0.0126


0.012606479227542877

In [270]:
# Evaluate the model
model_googl.evaluate(X_googl_test, y_googl_test)

25/25 [==============================] - 1s 28ms/sample - loss: 0.0015


0.0014780181227251887

In [271]:
# Make some predictions
predicted_fb = model_fb.predict(X_fb_test)

In [278]:
# Make some predictions
predicted_aapl = model_aapl.predict(X_aapl_test)

In [279]:
# Make some predictions
predicted_amzn = model_amzn.predict(X_amzn_test)

In [280]:
# Make some predictions
predicted_nflx = model_nflx.predict(X_nflx_test)

In [281]:
# Make some predictions
predicted_googl = model_googl.predict(X_googl_test)

In [282]:
# Recover the original prices instead of the scaled version
predicted_prices_fb = scaler.inverse_transform(predicted_fb)
predicted_prices_fb

array([[1319.9994],
       [1320.4341],
       [1318.6104],
       [1326.3865],
       [1327.7837],
       [1329.4465],
       [1323.9917],
       [1320.0809],
       [1299.9037],
       [1302.8093],
       [1305.241 ],
       [1303.7534],
       [1303.2571],
       [1314.9819],
       [1297.9622],
       [1272.9573],
       [1265.541 ],
       [1267.843 ],
       [1280.5214],
       [1299.3088],
       [1314.7535],
       [1321.7181],
       [1326.9797],
       [1335.9724],
       [1340.2369]], dtype=float32)

In [283]:
# Recover the original prices instead of the scaled version
predicted_prices_aapl = scaler.inverse_transform(predicted_aapl)
predicted_prices_aapl

array([[1310.08  ],
       [1309.5859],
       [1310.0101],
       [1311.8889],
       [1312.5552],
       [1313.0559],
       [1314.3425],
       [1314.5874],
       [1312.4576],
       [1313.658 ],
       [1316.9984],
       [1315.7539],
       [1320.1896],
       [1325.2615],
       [1326.1891],
       [1327.0085],
       [1326.6853],
       [1329.9847],
       [1332.0432],
       [1334.0905],
       [1333.184 ],
       [1332.3347],
       [1334.4545],
       [1337.679 ],
       [1340.8368]], dtype=float32)

In [284]:
# Recover the original prices instead of the scaled version
predicted_prices_amzn = scaler.inverse_transform(predicted_amzn)
predicted_prices_amzn

array([[1150.6273],
       [1147.3771],
       [1153.7758],
       [1170.6841],
       [1191.6873],
       [1202.5017],
       [1210.603 ],
       [1206.9858],
       [1194.2025],
       [1176.4542],
       [1165.703 ],
       [1157.5876],
       [1153.9698],
       [1150.0337],
       [1149.6338],
       [1151.4459],
       [1157.1997],
       [1172.3618],
       [1186.7161],
       [1197.1249],
       [1203.5607],
       [1205.0708],
       [1198.9093],
       [1229.167 ],
       [1271.9397]], dtype=float32)

In [285]:
# Recover the original prices instead of the scaled version
predicted_prices_nflx = scaler.inverse_transform(predicted_nflx)
predicted_prices_nflx

array([[1163.3606],
       [1172.8026],
       [1181.0488],
       [1185.4158],
       [1195.5636],
       [1207.165 ],
       [1211.0089],
       [1205.4772],
       [1191.3457],
       [1179.5056],
       [1174.4744],
       [1170.5918],
       [1161.2339],
       [1146.5887],
       [1137.2018],
       [1133.8065],
       [1136.498 ],
       [1146.6707],
       [1158.9421],
       [1178.1284],
       [1201.7894],
       [1230.0685],
       [1255.9932],
       [1271.2052],
       [1276.6526]], dtype=float32)

In [286]:
# Recover the original prices instead of the scaled version
predicted_prices_googl = scaler.inverse_transform(predicted_googl)
predicted_prices_googl

array([[1320.2158],
       [1318.6409],
       [1316.0092],
       [1323.2969],
       [1328.9199],
       [1323.5428],
       [1307.4502],
       [1307.7478],
       [1319.2668],
       [1332.5791],
       [1341.3253],
       [1339.444 ],
       [1345.8239],
       [1350.7324],
       [1351.6162],
       [1344.8153],
       [1352.919 ],
       [1350.6687],
       [1351.5615],
       [1352.0287],
       [1349.1486],
       [1349.9941],
       [1353.8846],
       [1356.9363],
       [1355.464 ]], dtype=float32)

In [287]:
real_prices_fb = scaler.inverse_transform(y_fb_test.reshape(-1, 1))
real_prices_aapl = scaler.inverse_transform(y_aapl_test.reshape(-1, 1))
real_prices_amzn = scaler.inverse_transform(y_amzn_test.reshape(-1, 1))
real_prices_nflx = scaler.inverse_transform(y_nflx_test.reshape(-1, 1))
real_prices_googl = scaler.inverse_transform(y_googl_test.reshape(-1, 1))

In [288]:
# Create a DataFrame of Real and Predicted values
fb_stocks = pd.DataFrame({
    "Real": real_prices_fb.ravel(),
    "Predicted": predicted_prices_fb.ravel()
})
fb_stocks.head(10)

Real    Predicted
0  1315.884922  1319.999390
1  1320.251442  1320.434082
2  1315.483403  1318.610352
3  1331.544167  1326.386475
4  1329.837711  1327.783691
5  1319.950303  1329.446533
6  1315.633972  1323.991699
7  1314.981504  1320.080933
8  1318.344226  1299.903687
9  1326.725938  1302.809326

In [289]:
# Create a DataFrame of Real and Predicted values
aapl_stocks = pd.DataFrame({
    "Real": real_prices_aapl.ravel(),
    "Predicted": predicted_prices_aapl.ravel()
})
aapl_stocks.head(10)

Real    Predicted
0  1294.280365  1310.079956
1  1304.710422  1309.585938
2  1299.427074  1310.010132
3  1308.080606  1311.888916
4  1306.441174  1312.555176
5  1299.404301  1313.055908
6  1288.997016  1314.342529
7  1294.052634  1314.587402
8  1302.797486  1312.457642
9  1314.457288  1313.657959

In [290]:
# Create a DataFrame of Real and Predicted values
amzn_stocks = pd.DataFrame({
    "Real": real_prices_amzn.ravel(),
    "Predicted": predicted_prices_amzn.ravel()
})
amzn_stocks.head(10)

Real    Predicted
0  1157.899543  1150.627319
1  1178.566855  1147.377075
2  1195.863852  1153.775757
3  1211.631587  1170.684082
4  1198.811023  1191.687256
5  1184.446350  1202.501709
6  1176.072525  1210.603027
7  1168.760275  1206.985840
8  1153.913067  1194.202515
9  1162.160691  1176.454224

In [291]:
# Create a DataFrame of Real and Predicted values
nflx_stocks = pd.DataFrame({
    "Real": real_prices_nflx.ravel(),
    "Predicted": predicted_prices_nflx.ravel()
})
nflx_stocks.head(10)

Real    Predicted
0  1177.527077  1163.360596
1  1190.382522  1172.802612
2  1181.316833  1181.048828
3  1191.001763  1185.415771
4  1187.979867  1195.563599
5  1176.362904  1207.165039
6  1166.727512  1211.008911
7  1162.145128  1205.477173
8  1158.652609  1191.345703
9  1169.551252  1179.505615

In [292]:
# Create a DataFrame of Real and Predicted values
googl_stocks = pd.DataFrame({
    "Real": real_prices_googl.ravel(),
    "Predicted": predicted_prices_googl.ravel()
})
googl_stocks.head(10)

Real    Predicted
0  1294.16  1320.215820
1  1305.65  1318.640869
2  1313.01  1316.009155
3  1312.46  1323.296875
4  1304.20  1328.919922
5  1288.86  1323.542847
6  1293.86  1307.450195
7  1318.30  1307.747803
8  1327.56  1319.266846
9  1339.41  1332.579102

In [293]:
# Plot the real vs predicted prices as a line chart
fb_stocks.hvplot(title = "fb")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [294]:
# Plot the real vs predicted prices as a line chart
aapl_stocks.hvplot(title = "aapl")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [295]:
# Plot the real vs predicted prices as a line chart
amzn_stocks.hvplot(title = "amzn")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [296]:
# Plot the real vs predicted prices as a line chart
nflx_stocks.hvplot(title = "nflx")

:NdOverlay   [Variable]
   :Curve   [index]   (value)

In [297]:
# Plot the real vs predicted prices as a line chart
googl_stocks.hvplot(title = "googl")

:NdOverlay   [Variable]
   :Curve   [index]   (value)